# .github/workflows/release.yml

name: CI/CD

# This workflow is triggered on pushes to the main branch.
# It handles both building the project and creating a semantic release.
on:
  push:
    branches:
      - main

jobs:
  build:
    # This job builds the Rust project and uploads the binary as an artifact.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build project
        run: cargo build --verbose --release
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: kairos
          path: target/release/kairos_cli

  release:
    # This job runs after the 'build' job has successfully completed.
    # It downloads the artifact and then creates a release using semantic-release.
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install semantic-release dependencies
        run: npm install semantic-release @semantic-release/exec @semantic-release/github @semantic-release/commit-analyzer @semantic-release/release-notes-generator
      - name: Download kairos binary artifact
        uses: actions/download-artifact@v4
        with:
          name: kairos
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
